server:
  port: 8080

spring:
  datasource:
    jdbc-url: jdbc:postgresql://localhost:5332/bj
    username: brayan
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    loggers: slf4j
logging:
  level:
    org.flywaydb: DEBUG
    org.springframework.boot.autoconfigure.orm.jpa: DEBUG